export const tags = [
    {title: 'action'},
    {title: 'adventure'},
    {title: 'animation'},
    {title: 'biography'},
    {title: 'comedy'},
    {title: 'crime'},
    {title: 'drama'},
    {title: 'family'},
    {title: 'fantasy'},
    {title: 'film-noir'},
    {title: 'history'},
    {title: 'horror'},
    {title: 'music'},
    {title: 'musical'},
    {title: 'mystery'},
    {title: 'romance'},
    {title: 'sci-fi'},
    {title: 'sport'},
    {title: 'thriller'},
    {title: 'war'},
    {title: 'western'},
];